packages:
  - packages/*
  - demos/*

catalog:
  '@commitlint/cli': '^21.0.1'
  '@commitlint/config-conventional': '^21.0.1'
  '@custom-elements-manifest/analyzer': '^0.11.0'
  '@custom-elements-manifest/to-markdown': '^0.1.0'
  '@floating-ui/dom': '^1.7.6'
  '@tailwindcss/vite': '^4.3.0'
  '@types/node': '^25.9.1'
  autoprefixer: '^10.5.0'
  browserslist: '^4.28.2'
  css-extras: '^0.4.0'
  csskit: '^0.0.23'
  embla-carousel: '^8.6.0'
  embla-carousel-autoplay: '^8.6.0'
  iconify-icon: '^3.0.2'
  lit: '^3.3.3'
  postcss: '^8.5.15'
  postcss-import: '^16.1.1'
  tailwindcss: '^4.3.0'
  tinyglobby: '^0.2.16'
  typescript: '^6.0.3'
  vite: '^8.0.14'
  vite-plugin-dts: '^5.0.1'
  vite-plus: '^0.1.22'
  vitepress: '2.0.0-alpha.17'
