packages:
  - packages/*
  - demos/*

catalog:
  '@commitlint/cli': '^21.0.2'
  '@commitlint/config-conventional': '^21.0.2'
  '@custom-elements-manifest/analyzer': '^0.11.0'
  '@custom-elements-manifest/to-markdown': '^0.1.0'
  '@floating-ui/dom': '^1.7.6'
  '@tailwindcss/vite': '^4.3.1'
  '@tiptap/core': '^3.27.1'
  '@tiptap/extension-highlight': '^3.27.1'
  '@tiptap/extensions': '^3.27.1'
  '@tiptap/pm': '^3.27.1'
  '@tiptap/starter-kit': '^3.27.1'
  '@types/node': '^26.0.0'
  autoprefixer: '^10.5.0'
  browserslist: '^4.28.2'
  css-extras: '^0.4.0'
  csskit: '^0.0.25'
  embla-carousel: '^8.6.0'
  embla-carousel-autoplay: '^8.6.0'
  emoji-picker-element: '^1.29.1'
  iconify-icon: '^3.0.2'
  lit: '^3.3.3'
  postcss: '^8.5.15'
  postcss-import: '^16.1.1'
  tailwindcss: '^4.3.1'
  tinyglobby: '^0.2.17'
  typescript: '^6.0.3'
  vite: '^8.0.16'
  vite-plugin-dts: '^5.0.2'
  vite-plus: '^0.2.1'
  vitepress: '2.0.0-alpha.17'
