import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { Plugin } from 'vite-plus';
import postcssPrefix from './postcss-plugin-prefix.js';

/**
 * Map of element base name → class name as exported by `luxen-ui/<name>/element`.
 * Keep in sync with `src/html/registry.ts` `ElementBaseName`.
 */
const ELEMENT_CLASSES: Record<string, string> = {
  avatar: 'Avatar',
  badge: 'Badge',
  carousel: 'Carousel',
  'carousel-item': 'CarouselItem',
  dialog: 'Dialog',
  divider: 'Divider',
  drawer: 'Drawer',
  dropdown: 'Dropdown',
  'dropdown-item': 'DropdownItem',
  icon: 'Icon',
  'input-otp': 'InputOtp',
  'input-stepper': 'InputStepper',
  popover: 'Popover',
  rating: 'Rating',
  skeleton: 'Skeleton',
  spinner: 'Spinner',
  'sticky-bar': 'StickyBar',
  stories: 'LuxenStories',
  'stories-viewer': 'LuxenStoriesViewer',
  story: 'LuxenStory',
  tabs: 'Tabs',
  toast: 'Toast',
  'toast-item': 'ToastItem',
  tooltip: 'Tooltip',
  tree: 'Tree',
  'tree-item': 'TreeItem',
};

const HEADER_MARKER = '// luxen-ui: prefix-aware HTMLElementTagNameMap';

export interface EmitTypesOptions {
  /** Where to write the .d.ts (relative to the project root). */
  path: string;
  /** Subset of element base names. Defaults to all elements. */
  elements?: readonly string[];
  /** Overwrite the file even when it exists. Default `false`. */
  force?: boolean;
}

export interface LuxenOptions {
  /** Custom element tag name prefix. Default `'l'`. */
  elementPrefix?: string;
  /** CSS class/token/keyframe prefix. Default `'l'`. */
  cssPrefix?: string;
  /**
   * Emit a project-local `.d.ts` that augments `HTMLElementTagNameMap` with
   * the configured prefix so templates type-check. Pass a string for the
   * default behaviour (write once, never overwrite), or an object for finer
   * control. The file is written into the consumer's source tree — commit it
   * and edit freely.
   */
  emitTypes?: string | EmitTypesOptions;
}

export default function luxen(options: LuxenOptions = {}): Plugin {
  const elementPrefix = options.elementPrefix || 'l';
  const cssPrefix = options.cssPrefix || 'l';

  if (options.emitTypes) {
    const cfg: EmitTypesOptions =
      typeof options.emitTypes === 'string' ? { path: options.emitTypes } : options.emitTypes;
    syncTypesFile(elementPrefix, cfg);
  }

  return {
    name: 'luxen',

    config() {
      if (elementPrefix === 'l' && cssPrefix === 'l') return;
      return {
        css: {
          postcss: {
            plugins: [postcssPrefix({ elementPrefix, cssPrefix })],
          },
        },
      };
    },
  };
}

function syncTypesFile(prefix: string, cfg: EmitTypesOptions): void {
  const target = resolve(process.cwd(), cfg.path);
  const names = cfg.elements ?? Object.keys(ELEMENT_CLASSES);
  const unknown = names.filter((n) => !(n in ELEMENT_CLASSES));
  if (unknown.length > 0) {
    console.warn(`[luxen] emitTypes: unknown element(s) ignored — ${unknown.join(', ')}`);
  }

  const content = renderTypesFile(
    prefix,
    names.filter((n) => n in ELEMENT_CLASSES),
  );

  if (existsSync(target)) {
    if (cfg.force) {
      writeFileSync(target, content, 'utf8');
      console.log(`[luxen] rewrote ${cfg.path} (force: true)`);
      return;
    }
    // Drift check: only flag files we previously wrote (signed with the marker).
    const current = readFileSync(target, 'utf8');
    if (current.includes(HEADER_MARKER) && !current.includes(`'${prefix}-`)) {
      console.warn(
        `[luxen] ${cfg.path} was generated for a different prefix than '${prefix}-*' — pass emitTypes: { path, force: true } to regenerate.`,
      );
    }
    return;
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');
  console.log(`[luxen] wrote ${cfg.path} — commit this file.`);
}

function renderTypesFile(prefix: string, names: readonly string[]): string {
  const sorted = [...names];
  sorted.sort();
  const imports = sorted
    .map((n) => `import type { ${ELEMENT_CLASSES[n]} } from 'luxen-ui/${n}/element';`)
    .join('\n');
  const entries = sorted.map((n) => `    '${prefix}-${n}': ${ELEMENT_CLASSES[n]};`).join('\n');

  return `${HEADER_MARKER}
// Generated by 'luxen-ui/vite-plugin' (emitTypes). You own this file — edit,
// drop elements you don't use, or regenerate by deleting it and re-running
// the dev/build command.

${imports}

declare global {
  interface HTMLElementTagNameMap {
${entries}
  }
}

export {};
`;
}
