# Project — {{displayName}} mockups

This project produces standalone HTML mockups using **{{displayName}}**, a CSS-first web component library. All design system assets are bundled **locally** under `{{name}}/assets/` — no CDN dependency.

The design system files live in `{{name}}/` (generated by `npx luxen-ui generate-skill` — do not edit by hand).

## Setup guide — read this first

→ **[`{{name}}/references/mockups.md`](./{{name}}/references/mockups.md)**

It covers, in order:
1. The HTML `<head>` boilerplate — one `<link>` to `assets/{{name}}-standalone.css` and one `<script type="module">` to `assets/{{name}}-standalone.js`. Two lines, all elements registered.
2. The list of all available `<l-*>` tags (every tag below is in the bundle, no per-element import needed)
3. Pointer to `references/<name>.md` for each element's attributes/slots/events
4. Don'ts (no Tailwind classes — {{displayName}} tokens only)

Read it before writing any mockup.

## Component reference

→ **[`{{name}}/SKILL.md`](./{{name}}/SKILL.md)** (entry point)
→ **[`{{name}}/references/<element>.md`](./{{name}}/references/)** (per-element specs)

For each component used (`l-dialog`, `l-toast`, `.l-button`, …), open the matching file in `{{name}}/references/` for its attributes, slots, events, and CSS custom properties.

## Workflow

1. Read `{{name}}/references/mockups.md` once at the start of the session.
2. For each component planned, read `{{name}}/references/<name>.md`.
3. Write the standalone HTML mockup:
   - Drop in the two-line boilerplate from `mockups.md`
   - Use any `<l-*>` tag freely — all are registered by the bundle

## When in doubt

- **Don't invent attributes.** If the per-element reference doesn't mention an attribute, it doesn't exist.
- **Don't use Tailwind utility classes** for colors, spacing, or layout — the bundle ships {{displayName}} only. Use the `--l-*` design tokens (defined in `{{name}}/assets/{{name}}-standalone.css`) and plain CSS instead.
- **Don't try to load individual element files** — the standalone bundle includes everything. Two assets, that's it.

## Updating

The skill is regenerated locally. After bumping `luxen-ui` or changing your brand tokens, re-run `npx luxen-ui generate-skill` and re-upload the updated `{{name}}/` folder.
